[package]
name = "headr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = "2.33"
pretty_assertions = "1.4.1"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
